### ISSUE TITLE
【建议】使用editorconfig配置文本编码

### ISSUE THREAD

**Issue by tytannial** [sigeer/Cosmic_DotNet#127]
配置后，只要编辑文本会自动保存固定的编码，防止乱码

使用全局配置

[*]
end_of_line = crlf # 换行风格
charset = utf-8 # 固定UTF8编码
insert_final_newline = true # 这条看实际操作，如果不喜欢可以不用，会自动在文件末尾保留一行空行

**Comment by sigeer** [comment]
感谢建议😄

**Comment by tytannial** [comment]
> 感谢建议😄

🤣最近没时间折腾了，挺想帮你的，前面我也折腾了一版C#的冒冒服务端。有空可能我陪你折腾一番，不过我用的数据库是postgresql。

**Comment by sigeer** [comment]
> > 感谢建议😄
> 
> 🤣最近没时间折腾了，挺想帮你的，前面我也折腾了一版C#的冒冒服务端。有空可能我陪你折腾一番，不过我用的数据库是postgresql。

哈哈，我也是摸鱼瞎折腾。
